export const MAIN_PAGE_UL = "https://kion.ru/"
export const AUTHORIZE_BUTTON_FROM_HEADER = "xpath=.//button[text()='Войти']"
export const MTS_LOGIN_FORM = "xpath=.//h1[text()='Введите номер телефона любого оператора']"
export const MTS_LOGIN_INPUT = "xpath=.//input[@id='login']"
export const MTS_LOGIN_PAGE_LOGIN_BUTTON = "xpath=.//button[text()='Далее']"
export const SIMILAR_SHELF = "xpath=.//section[@class='container-kion ng-star-inserted']"
export const MTS_LOGIN_OTP_INPUT = "xpath=.//input[@id='otp']"
export const VIDEO_BANNER = "xpath=.//div[@class='banner-carousel-container']"
export const VIDEO_BANNER_ACTIVE_ELEM = "xpath=.//li[contains(@class, 'carousel-card-active')]"
export const MY_PROFILE = "xpath=.//a[@href='/my/profile']"
export const PARENT_CONTROL = "xpath=.//.//ui-web-dropdown-button"
export const PARENT_CONTROL_6 = "xpath=.//p[text()=' До 6 лет ']"
export const SAVE_PARENT_CONTROL = "xpath=.//span[text()='Сохранить']"
export const USER_AGREEMENT_URL = "https://kion.ru/user-agreement"
export const FEEDBACK_PAGE_URL = "https://kion.ru/feedback"
export const USER_AGREEMENT_TITLE = "xpath=.//h2[text()='Пользовательское соглашение']"
export const USER_AGREEMENT_TEXT = "Настоящее Соглашение в соответствии со ст. 435"
export const USER_AGREEMENT_CHECKBOX = "xpath=.//input[@type='checkbox']"
export const FEEDBACK_EMAIL_INPUT = "xpath=.//input[@id='email']"
export const PIN_CODE_INPUT = "xpath=.//input[@id='inputNumber0']"
export const VIDEO_BANNER_LIST = "xpath=.//li[contains(@class, 'ng-carousel-slide allow-transition')]"
export const MY_PROFILE_BUTTON = "xpath=.//a[@href='/my/profile']"
export const TV_SHELF = "xpath=.//h2[text()='Сейчас на ТВ']"
export const FOOTER = "xpath=.//footer"
export const RIGHT_ARROW = "xpath=//div[contains(@class, 'ui-row-arrow-right')]"
export const VIDEO_SHELF = "xpath=.//ui-web-banners-carousel[2]"
export const AGE_DIALOG = "xpath=.//div[contains(@class, 'dialog-18')]"
export const AGE_YES = "xpath=.//span[text()='Да, я взрослый']"
export const CARD_CONTENT = "xpath=.//web-movie-card"