export const MAIN_PAGE_UL = "https://kion.ru/"
export const AUTHORIZE_BUTTON_FROM_HEADER = "xpath=.//button[text()='Войти']"
export const MTS_LOGIN_FORM = "xpath=.//h1[text()='Введите номер телефона любого оператора']"
export const MTS_LOGIN_INPUT = "xpath=.//input[@id='login']"
export const MTS_LOGIN_PAGE_LOGIN_BUTTON = "xpath=.//button[text()='Далее']"
export const SIMILAR_SHELF = "xpath=.//section[@class='container-kion ng-star-inserted']"
export const MTS_LOGIN_OTP_INPUT = "xpath=.//input[@id='otp']"
export const VIDEO_BANNER = "xpath=.//div[@class='banner-carousel-container']"
export const VIDEO_BANNER_ACTIVE_ELEM = "xpath=.//li[contains(@class, 'carousel-card-active')]"
export const MY_PROFILE = "xpath=.//a[@href='/my/profile']"
export const PARENT_CONTROL = "xpath=.//.//ui-web-dropdown-button"
export const SAVE_PARENT_CONTROL = "xpath=.//span[text()='Сохранить']"
export const PIN_CODE_INPUT = "xpath=.//input[@id='inputNumber0']"
export const VIDEO_BANNER_LIST = "xpath=.//li[contains(@class, 'ng-carousel-slide allow-transition')]"
export const MY_PROFILE_BUTTON = "xpath=.//a[@href='/my/profile']"
export const TV_SHELF = "xpath=.//h2[text()='Сейчас на ТВ']"
export const FOOTER = "xpath=.//footer"
export const RIGHT_ARROW = "xpath=//div[contains(@class, 'ui-row-arrow-right')]"
export const VIDEO_SHELF = "xpath=.//ui-web-banners-carousel[2]"
export const AGE_DIALOG = "xpath=.//div[contains(@class, 'dialog-18')]"
export const AGE_YES = "xpath=.//span[text()='Да, я взрослый']"
export const CARD_CONTENT = "xpath=.//web-movie-card"
export const SHELF = "xpath=.//ui-web-row[1]"
export const SHELF_POSTER_ITEM = "xpath=.//a[@class='web-row-item movie-poster-item'][1]"
export const LEFT_ARROW = "xpath=//div[contains(@class, 'ui-row-arrow-left')]"
export const FAVORITE_TV_SHELF = "xpath=.//h2[text()='Любимые телеканалы']"
export const LOGOUT_BUTTON = "xpath=.//span[text()='Выйти']"
export const LOGOUT_MODAL = "xpath=.//div[@class='ui-web-modal-scroll']"
export const LOGOUT_YES = "xpath=.//button[text()='Да']"
export const PREMIUM_MODAL = "xpath=.//div[contains(@class, 'ui-web-modal-scroll')]"
export const MODAL_CLOSE_BUTTON = "xpath=.//button[@class='close-button']"